### ISSUE TITLE
How to use the ReactiveMongoApi in tests

### ISSUE THREAD

**Issue by manuelbernhardt** [ReactiveMongo/Play-ReactiveMongo#141]
I know this may not necessarily be a `ReactiveMongoApi` issue but I can seem to use other components in tests, while this fails.

I have

```scala

class MongoStatisticsRepository @Inject() (reactiveMongo: DefaultReactiveMongoApi) extends StatisticsRepository { ... }
```

and in a specs2 test I try to do 

```scala
val repository = new MongoStatisticsRepository(app.injector.instanceOf[DefaultReactiveMongoApi])
```

but all I get is a

```
[info] The StatisticsService should
[error]   ! compute and publish statistics
[error]    Guice configuration errors:
[error]
[error]    1) No implementation for play.modules.reactivemongo.ReactiveMongoApi was bound.
[error]      while locating play.modules.reactivemongo.ReactiveMongoApi
[error]
[error]    1 error (InjectorImpl.java:1042)
[error] com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1042)
```

Is there anything I need to do additionally in order to get the API to be injected?

**Comment by cchantep** [comment]
Hi,

This has to do with Play 2.4 DI and how to use its [Guice app builder during test]( https://www.playframework.com/documentation/2.4.0/ScalaTestingWithGuice). You can find an [example](https://github.com/ReactiveMongo/Play-ReactiveMongo/blob/master/src/test/scala/PlaySpec.scala) in the tests of the ReactiveMongo module.

Please note that the [user MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) is where to ask such question, rather than this issue tracker.

Best regards
